pipeline {
    agent any

    tools {
      maven 'localMaven'
      git 'localGit'
    }

    triggers {
         pollSCM('* * * * *')
     }

stages{
        stage('Maven Build'){
            steps {
              sh 'mvn clean package'
            }
        }
        stage('Build'){
            steps {
                sh 'tree'
                sh 'docker build . -t dkheyman/trial-repo'
                sh 'docker push dkheyman/trial-repo'
            }
            post {
                success {
                    echo 'Successfully built docker image'
                }
            }
        }

        stage ('Deployments'){
            parallel{
                stage ('Deploy to Staging'){
                    steps {
                        sh "cat init.sh | ssh ec2-user@20.0.3.28 -i /var/lib/jenkins/.ssh/ec2 'bash -ex' "
                    }
                }

                stage ("Deploy to Production"){
                    steps {
                        sh "cat init.sh | ssh ec2-user@20.0.3.15 -i /var/lib/jenkins/.ssh/ec2 'bash -ex' "
                    }
                }
            }
        }
    }
}
